---
booktitle: Proceedings of the 1st Conference on Topology, Algebra, and Geometry in
  Data Science(TAG-DS 2025)
shortname: TAGDS2025
volume: '321'
year: '2025'
start: &1 2025-12-01
end: 2025-12-02
published: 2026-02-27
conference_number: '1'
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: TAGDS2025
month: 0
cycles: false
bibtex_editor: Bernardez Gil, Guillermo and Black, Mitchell and Cloninger, Alexander
  and Doster, Timothy and Emerson, Tegan and Garc{\'\i}a-Rodondo, I\'{n}es and Holtz,
  Chester and Kotak, Mit and Kvinge, Henry and Mishne, Gal and Papillon, Mathilde
  and Pouplin, Alison and Rainey, Katie and Rieck, Bastian and Telyatnikov, Lev and
  Yeats, Eric and Wang, Qingsong and Wang, Yusu and Wayland, Jeremy
editor:
- given: Guillermo
  family: Bernardez Gil
- given: Mitchell
  family: Black
- given: Alexander
  family: Cloninger
- given: Timothy
  family: Doster
- given: Tegan
  family: Emerson
- given: Ińes
  family: Garcı́a-Rodondo
- given: Chester
  family: Holtz
- given: Mit
  family: Kotak
- given: Henry
  family: Kvinge
- given: Gal
  family: Mishne
- given: Mathilde
  family: Papillon
- given: Alison
  family: Pouplin
- given: Katie
  family: Rainey
- given: Bastian
  family: Rieck
- given: Lev
  family: Telyatnikov
- given: Eric
  family: Yeats
- given: Qingsong
  family: Wang
- given: Yusu
  family: Wang
- given: Jeremy
  family: Wayland
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the 1st Conference on Topology, Algebra, and Geometry in Data Science(TAG-DS 2025)
    Held in San Diego, California, USA on 01-02 December 2025

  Published as Volume 321 by the Proceedings of Machine Learning Research on 27 February 2026.

  Volume Edited by:
    Guillermo Bernardez Gil
    Mitchell Black
    Alexander Cloninger
    Timothy Doster
    Tegan Emerson
    Ińes Garcı́a-Rodondo
    Chester Holtz
    Mit Kotak
    Henry Kvinge
    Gal Mishne
    Mathilde Papillon
    Alison Pouplin
    Katie Rainey
    Bastian Rieck
    Lev Telyatnikov
    Eric Yeats
    Qingsong Wang
    Yusu Wang
    Jeremy Wayland

  Series Editors:
    Neil D. Lawrence
date_str: 01--02 Dec
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v321"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v321
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v321
email: ''
conference:
  name: Topology, Algebra, and Geometry in Data Science(TAG-DS 2025)
  url: https://www.tagds.com/events/tag-ds-2025
  location: San Diego, California, USA
  dates:
  - *1
  - 2025-12-02
analytics:
  google:
    tracking_id: UA-92432422-1
link_visibility:
  openreview: true
  pdf: true
  supplementary: true
  software: true
  video: true
  arxiv: true
  doi: true
  website: true
orig_bibfile: TAGDS2025_cleaned_clean.bib
# Site settings
# Original source:  TAGDS2025_cleaned_clean.bib
